### ISSUE TITLE
Lab 3 Cat Mismatches

### ISSUE THREAD

**Issue by TytanRock** [frap129/CS231#1]
Some things that got missed in testing.
 - [x] Using multiple '-' in command arguments: `./kat - -` should prompt user twice, but currently only prompts once
 - [x] Spacing for line numbers: `./kat kat.c -n` will ensure 6(?) *spaces* before *line numbers*, followed by line number and a tab, whereas `cat main.c -n` will ensure 9(?) **total** characters before **output** is reached, example output:
``` 
./kat
     7  #include <stdlib.h>$
     8  #include <string.h>$
     9  $
     10 #define B_INDEX 0$
     11 #define E_INDEX 1$
     12 #define N_INDEX 2$
     13 $
```

``` 
cat
     7  #include <stdlib.h>$
     8  #include <string.h>$
     9  $
    10  #define B_INDEX 0$
    11  #define E_INDEX 1$
    12  #define N_INDEX 2$
    13  $
```

**Comment by frap129** [comment]
I've fixed both of these issues, still having trouble with having to double Ctrl+^D to print the line
