### ISSUE TITLE
Double closing pipes in project 4

### ISSUE THREAD

**Issue by TytanRock** [frap129/CS231#2]
I see that in project 4, under spellcheck.c, you double close some pipes. This leads to undefined behavior.

https://github.com/frap129/CS231/blob/7f589093416199239bacc235ba269a395f958134/lab4/spellCheck.c#L91-L96
https://github.com/frap129/CS231/blob/7f589093416199239bacc235ba269a395f958134/lab4/spellCheck.c#L23-L24

Relevant code pasted here for posterity:
```
// Inside init_childs
close(lex2sort[1]); /* lex2Sort[1] is closed, and sort_child happens after */

// Above main
void sort_child(int in_pipe[2], int out_pipe[2]) {
    close(in_pipe[1]);//close write end, lex writes this /* THIS IS ALREADY CLOSED FROM ABOVE */
    dup2(in_pipe[0], STDIN_FILENO);
    close(in_pipe[0]); /* Now all lex2Sort pipes are closed, with pipe[1] closed twice */
```

**Comment by frap129** [comment]
Thanks again Cory, fixed in commit e7d1c0ef365dbff6f0e06cb9243fa7cf0eeae15a
